name: Build test

on:
  push:
    branches:
     - main
     - development
  pull_request:
    branches:
     - main
     - development
#  schedule:
    # Do a nightly run of the tests
#    - cron: '0 1 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#specifying-a-python-version
    strategy:
      matrix:
        python-version:  ["3.12"]
      # Complete all versions in matrix even if one fails.
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Python ${{ matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        # Version range or exact version of a Python version to use, using SemVer's version range syntax.
        python-version: ${{ matrix.python-version}}
        architecture: x64

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mpich
        pip install numpy mpi4py
        pip install petsc petsc4py

    - name: Set environment variables
      run: |
        echo "PETSC_DIR=/usr/local/petsc" >> $GITHUB_ENV
        echo "PETSC_ARCH=arch-linux-c-opt" >> $GITHUB_ENV

    - name: Install Hypre
      run: |
        git clone https://github.com/hypre-space/hypre.git
        cd hypre/src
        ./configure --with-MPI
        make
        sudo make install

    - name: Install MUMPS
      run: |
        git clone https://github.com/scivision/mumps.git
        cd mumps
        mkdir build
        cd build
        cmake -G "Ninja" -DMUMPS_parallel=on ..
        cmake --build .
        sudo make install

    - name: Install DarSIA
      run: pip install .[dev]

    - name: black
      if: ${{ always() }}
      run: black --check src

    - name: flake8
      if: ${{ always() }}
      run: flake8 src

    # - name: mypy
    #   if: ${{ always() }}
    #   run: mypy src

    - name: isort
      if: ${{always()}}
      run: isort --check src

    - name: pytest
      if: ${{always()}}
      run: pytest
